---
- name: run the main role
  hosts: all
  roles:
    - role: ansible-prometheus
      prometheus_conf_main: "prometheus/prometheus.yml"
      prometheus_alertmanager_conf: "prometheus/alertmanager.yml"
      prometheus_rule_files:
        basic_rules:
          src:  "prometheus/rules/basic.rules"
          dest: basic.rules
        black_box_rules:
          src:  "prometheus/rules/black_box.rules"
          dest: black_box.rules
    - role: cloudalchemy.grafana
      grafana_security: { admin_user: admin, admin_password: "admin" }
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: 'http://localhost:9090'
          basicAuth: false
      grafana_dashboards:
        - dashboard_id: 3681
          revision_id: 1
          datasource: prometheus
    - role: entercloudsuite.prometheus-exporter 
      prometheus_exporter_name: node_exporter
      prometheus_exporter_version: 0.16.0
    - role: entercloudsuite.prometheus-exporter
      prometheus_exporter_name: blackbox_exporter
      prometheus_exporter_version: 0.12.0
      prometheus_exporter_conf_main: "prometheus/config_blackbox_exporter.yaml"
      prometheus_exporter_config_flags:
        "--config.file": "{{ prometheus_exporter_custom_conf_destination }}/config_blackbox_exporter.yaml"
      tags: blackbox_exporter
    - role: entercloudsuite.consul
      consul_version: 1.2.3
      consul_packer_provision: true
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "K8n07GA/ZoANSmJ5zkvgOg=="
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
  
  post_tasks:
    - name: Register Prometheus GID
      command: id -g {{ prometheus_exporters_common_group }}
      register: command_output
    - set_fact:
        prometheus_exporters_common_git_user: "{{ command_output.stdout }}"
    - debug: msg="{{prometheus_exporters_common_git_user}}"
    - name: Register Prometheus UID
      command: id -u {{ prometheus_exporters_common_user }}
      register: command_output
    - set_fact:
        prometheus_exporters_common_uid_user: "{{ command_output.stdout }}"
    - debug: msg="{{prometheus_exporters_common_uid_user}}"
    - name: set sysctl factl
      set_fact:
        sysctl_ping_grop_range: " {{ prometheus_exporters_common_uid_user }} {{ prometheus_exporters_common_uid_user  | int +1 }}"
    - debug: msg="{{sysctl_ping_grop_range}}"
    - name: configre kernel for blackbox_expoter ping
      sysctl: 
        name: net.ipv4.ping_group_range
        value: "{{sysctl_ping_grop_range}}"
        sysctl_set: yes
        state: present
        reload: yes
- name: prepare virtualenv
  hosts: all
  tasks:
    - name: create var project path
      set_fact:
        script_path: /usr/src/cloud
    - name: install requirements
      package: name="{{ item }}"
      with_items:
        - libffi-dev
        - libssl-dev
        - python-minimal
        - python-pip
        - virtualenv
    - name: create directory
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ script_path }}"
        - "{{ script_path }}/roles"
    - name: create requirements.txt
      copy:
        content: |
          ansible==2.6.2
          asn1crypto==0.23.0
          bcrypt==3.1.4
          cffi==1.11.2
          cryptography==2.1.3
          enum34==1.1.6
          idna==2.6
          ipaddress==1.0.18
          Jinja2==2.10
          MarkupSafe==1.0
          paramiko==2.4.0
          pyasn1==0.3.7
          pycparser==2.18
          pycrypto==2.6.1
          PyNaCl==1.2.0
          PyYAML==3.12
          six==1.11.0
          jmespath==0.9.3
        dest: "{{ script_path }}/requirements.txt"
        remote_src: yes
    - name: create requirements.yml
      copy:
        content: |
          - src: entercloudsuite.consul
            version: 1.0.1
          - src: cloudalchemy.grafana
            version: 0.11.4
          - src: entercloudsuite.prometheus-exporter
            version: 1.0.4
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
    - name: install python requirements
      pip:
        requirements: "{{ script_path }}/requirements.txt"
        virtualenv: "{{ script_path }}/venv"
    - name: install ansible roles
      shell: source {{ script_path }}/venv/bin/activate && ansible-galaxy install -f -p roles -r requirements.yml
      args:
        chdir: "{{ script_path }}"
        executable: /bin/bash
